name: Publish
on: 
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
         os: [win-x64, osx-x64, linux-x64]


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore
        run: dotnet restore

      - name: Test
        run: dotnet test --verbosity normal

      - name: Build for all
        run: dotnet publish ./src/Chirp/chirp.csproj --no-restore --configuration Release -r ${{matrix.os}} --no-self-contained -p:PublishSingleFile=true 

      - name: Zipping files
        run: cd ./src/Chirp/bin/Release/net7.0/${{matrix.os}}/publish && zip ../../../../../../../Chirp-${{github.ref_name}}-${{matrix.os}}.zip Chirp.exe
        
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Chirp-${{github.ref_name}}-${{matrix.os}}.zip
        
